import fitz  # PyMuPDF
import google.generativeai as genai
from PIL import Image
import io

def extract_text_from_pdf(pdf_bytes: bytes) -> str:
    """Extracts text from a PDF file provided as bytes."""
    doc = fitz.open(stream=pdf_bytes, filetype="pdf")
    text = ""
    for page in doc:
        text += page.get_text()
    return text

async def analyze_medical_report(extraction_res: str, is_image: bool = False, file_bytes: bytes = None, is_pdf: bool = False):
    """
    Analyzes medical report text, image, or PDF using Gemini API.
    Returns a simplified explanation for patients.
    """
    # List of possible model names to try (handling different API versions/naming)
    # Based on your environment, these names are confirmed to be available:
    model_names = [
        'gemini-flash-latest',       # This is often the ID for 1.5 Flash in some regions
        'gemini-2.0-flash',          # A newer, very fast model confirmed in your list
        'gemini-1.5-flash', 
        'gemini-1.5-flash-latest', 
        'gemini-pro'
    ]
    
    last_error = None
    for model_name in model_names:
        try:
            model = genai.GenerativeModel(model_name)
            
            prompt = """
            You are an AI Medical Assistant specialized in simplifying complex medical reports for patients.
            Your goal is to explain the medical findings in clear, empathetic, and easy-to-understand language.
            
            ### Guidelines:
            1. **Simplify Jargon**: Explain medical terms (e.g., 'Hemolysis' -> 'Breakdown of red blood cells').
            2. **Summarize Findings**: Provide a high-level overview of what the report means.
            3. **Actionable Insights**: Suggest what the patient should discuss with their doctor (e.g., questions to ask).
            4. **Tone**: Empathetic, professional, and clear.
            5. **Disclaimer**: Always include a disclaimer that this is an AI analysis and not a substitute for professional medical advice.
            
            ### Report Content:
            {content}
            
            ### Output Format (Markdown):
            # Medical Report Simplified
            ## Summary
            [Brief summary of the report]
            
            ## Key Findings
            [List of important results explained simply]
            
            ## What This Means for You
            [Personalized explanation]
            
            ## Questions for Your Doctor
            [List of suggested questions]
            
            > **Disclaimer**: This analysis is generated by AI for informational purposes only. It is not a professional medical diagnosis or a substitute for a consultation with a healthcare provider.
            """
            
            if is_image and file_bytes:
                img = Image.open(io.BytesIO(file_bytes))
                response = model.generate_content([prompt.format(content="See attached medical report image."), img])
            elif is_pdf and file_bytes:
                doc = fitz.open(stream=file_bytes, filetype="pdf")
                if len(doc) > 0:
                    page = doc[0]
                    pix = page.get_pixmap()
                    img_data = pix.tobytes("png")
                    img = Image.open(io.BytesIO(img_data))
                    response = model.generate_content([prompt.format(content="See attached medical report (scanned PDF)."), img])
                else:
                    return "Error: The PDF file appears to be empty."
            else:
                response = model.generate_content(prompt.format(content=extraction_res))
            
            return response.text
        except Exception as e:
            last_error = e
            # If it's a 404, we continue to the next model name
            if "404" in str(e):
                continue
            else:
                # For other errors, we might want to raise them or continue
                continue
                
    raise last_error
